### ISSUE TITLE
Implementar LH y LB y SH y SB

### ISSUE THREAD

**Issue by brunoperezm** [gerlamberti/arq-tpfinal-lamberti-perez#16]

**Comment by brunoperezm** [comment]
Enmascaramiento. deberia ser igual que el LW y SW porque hacen lo mismo pero guardan o cargan con una máscara. 
Tieen que tener tb hechos.

**Comment by gerlamberti** [comment]
Ademas de hacer LH, LB, SH, SB, hice LHU, LBU, LWU.
