### ISSUE TITLE
Terminar el MUX del execute y forwarding. Con buenos nombres si puede ser jej.

### ISSUE THREAD

**Issue by brunoperezm** [gerlamberti/arq-tpfinal-lamberti-perez#23]
Hacer PR, no mergear directo.

**Comment by gerlamberti** [comment]
Listo bebe, ya entendí como funciona esto... es justamente para seleccionar si tiene que usar la data que viene del memory o del wb... con esto creo que solucionamos el problema que teniamos los otros días. Listo el forwarding. Viva peron.
